# permissions for end users to edit centrals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: central-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: central-operator
    app.kubernetes.io/part-of: central-operator
    app.kubernetes.io/managed-by: kustomize
  name: central-editor-role
rules:
- apiGroups:
  - media.flussonic.com
  resources:
  - centrals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - media.flussonic.com
  resources:
  - centrals/status
  verbs:
  - get
