## Append samples of your project ##
resources:
- https://flussonic.github.io/media-server-operator/latest/operator.yaml
- https://flussonic.github.io/watcher-operator/latest/operator.yaml
- media_v1alpha1_central.yaml
- media_v1alpha1_mediaserver.yaml
# - media_v1alpha1_watcher.yaml
- postgres.yaml
- redis.yaml
- ingress.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
