apiVersion: media.flussonic.com/v1alpha1
kind: Central
metadata:
  labels:
    app: central
  name: central
spec:
  database: "postgresql://test:test@postgres.default.svc.cluster.local:5432/test_c"
  redis: "redis://redis.default.svc.cluster.local:6379"
  version: "v25.04.1-21"
  apiKey: "apikey"
  apiURL: "http://central.default.svc.cluster.local"
  provisionerClusterKey: "clusterkey"
  provisionerSelector: "mediaserver-media-server"
  central:
    replicas: 2
    env:
      - name: CENTRAL_LICENSE_KEY
        valueFrom:
          secretKeyRef:
            name: flussonic-license
            key: license_key
            optional: false
      - name: CENTRAL_EDIT_AUTH
        value: "admin pass"
      - name: CENTRAL_LOG_LEVEL
        value: "debug"
      - name: CENTRAL_LOG_REQUESTS
        value: "true"
      - name: CENTRAL_CLUSTER_NODE_CONFIG_PROVISION_ENABLED
        value: "false"
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        value: "60s"
      - name: CENTRAL_LAYOUTER_SLEEPING_INTERVAL
        value: "10s"
  layouter:
    env:
      - name: CENTRAL_LAYOUTER_SLEEPING_INTERVAL
        value: "30s"
      - name: CENTRAL_LOG_LEVEL
        value: "debug"
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        value: "60s"
  agentsUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        value: "debug"
      - name: CENTRAL_LOG_REQUESTS
        value: "true"
  singletonUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        value: "debug"
      - name: CENTRAL_LOG_REQUESTS
        value: "true"
