apiVersion: media.flussonic.com/v1
kind: Central
metadata:
  labels:
    app.kubernetes.io/name: central
    app.kubernetes.io/instance: central-sample
    app.kubernetes.io/part-of: central-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: central-operator
  name: central-sample
spec:
  database: "postgresql://test:test@postgres.default.svc.cluster.local:5432/test_c"
  image: "flussonic/central:v24.03"
  api_key: "apikey"
  edit_auth: "admin pass"
  cluster_node_provision_enabled: "false"
  api_url: "http://central.svc.cluster.local"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-sample
spec:
  defaultBackend:
    service:
      name: central-sample-web
      port:
        number: 9019
