apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "postgres:15.3"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: test
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_DB
          value: test_c
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U "postgres" -h 127.0.0.1
          failureThreshold: 2
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 30
---
apiVersion: media.flussonic.com/v1alpha1
kind: Central
metadata:
  labels:
    app.kubernetes.io/name: central
    app.kubernetes.io/instance: central-sample
    app.kubernetes.io/part-of: central-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: central-operator
    app: central
  name: central-sample
spec:
  nodeSelector:
    flussonic.com/central: "true"
  database: "postgresql://test:test@postgres.default.svc.cluster.local:5432/test_c"
  image: "flussonic/central:v24.03"
  api_key: "apikey"
  edit_auth: "admin pass"
  api_url: "http://central-sample.default.svc.cluster.local"
  provisioner_cluster_key: "clusterkey"
  provisioner_selector: "mediaserver-sample-streamer"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-sample
spec:
  defaultBackend:
    service:
      name: central-sample
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: streamer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: streamer
  selector:
    app: streamer
---
apiVersion: media.flussonic.com/v1alpha1
kind: MediaServer
metadata:
  labels:
    app.kubernetes.io/name: mediaserver
    app.kubernetes.io/instance: mediaserver-sample
    app.kubernetes.io/part-of: media-server-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: media-server-operator
    app: streamer
  name: mediaserver-sample
spec:
  image: flussonic/flussonic:v24.02-107
  hostPort: 85
  nodeSelector:
    flussonic.com/streamer: "true"
  env:
    - name: LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: flussonic-license
          key: license_key
          optional: false
    - name: FLUSSONIC_CONFIG_EXTERNAL
      value: "http://apikey@central-sample.default.svc.cluster.local/streamer/api/v3/streamers/$(FLUSSONIC_HOSTNAME)"
  configExtra:
    watcher.conf: |
      cluster_key clusterkey;

